# Site config
title: Energy Research Digest
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Energy Research Digest, where I publish research summaries and policy commentary on different research topics centered around energy and its access in Africa
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://m-abdelshafy.github.io" # the base hostname & protocol for your site, e.g. http://example.com


####################################################################
# Policy-insights collection
####################################################################
collections:

  # keep any other collections you have here …

  policy-insights:            # folder name: “_policy-insights/”
    output:    true           # every file becomes its own page
    permalink: /policy-insights/:title/
    sort_by:   date           # newest first in our list below

# (optional) give all articles the same default layout so you
# don’t repeat “layout: policy-article” in every file
defaults:
  - scope:
      path: "_policy-insights"
    values:
      layout: policy-article        # make this file in _layouts/

# Author info
author-name: M. Y. Abdelshafy
author-avatar: avatar.png

# Connect
email: yasser.abdelshafy@rochester.edu
github-username: m-abdelshafy
youtube-username: Mottagah3409

# Post Paths
permalink: /blog/:categories/:year/:month/:day/:title:output_ext
paginate_path: "/blog/page:num/"

# Pagination (Posts shown before page 2)
paginate: 8

# Syntax highlighting
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids: true
  hard_wrap: false

# Allow future posts if set to true
future: true

#Jekyll Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# SEO
twitter:
  username: shadow_stack
  card: summary

# disqus comments
disqus:
  shortname:
